### ISSUE TITLE
Increase timeout to 60 seconds to accomodate hobby projects

### ISSUE THREAD

**Issue by ahmedsadman** [pschlan/cron-job.org#275]
Hi,
Many of us use tools like cron-job in conjunction with hobby projects, which are often hosted in free-tier servers. Free-tier servers automatically sleep after certain amount of delay. So, any sudden request can take more than 30 seconds to return a success response, causing cron-job to mark it as failure. Can we increase it to 60 seconds or more?

**Comment by ahmedsadman** [comment]
@pschlan Can you please have a look on this? Not seeing any activity after quite some time

**Comment by pschlan** [comment]
Hi,

I can't increase the limit without significantly expanding computing resources for the service. I don't want to put ads on the site or use other shady ways to finance that. The service has the promise to be fair, treat customer data with respect and don't sell out. I can only keep that promise with certain limits in place. 

Specifically for your issue, I see these possible solutions:
- Call your URL every minute or so to prevent your service/lambda/... to go to sleep in the first place 
- Become a sustaining member with increased limits, starting at 12 EUR/year, and support the service by doing so
- Use another service which might have higher limits, but might treat you as the product instead of the customer 

Sorry I can't provide a more satisfactory answer here.

**Comment by pschlan** [comment]
There one other option to make this work in a sub optimal way using cron-job.org without any charges. Please email me at info@cron-job.org as I can't share the details in public.

**Comment by ahmedsadman** [comment]
I have rechecked the responses. It seems it's not about timeout (at least not anymore). The request immediately hits a 503 Service Unavailable. Most probably it filters based on the User-Agent header @pschlan

**Comment by pschlan** [comment]
If they want to block the jobs, they will block them. If it's not the user agent, they will use the service IP addresses. There's not much we can do about that...
